# We like to use pre-commit but we prefer not to combine pre-commit/psf-black fixes with the commit step.
# Instead, we block pushes until things get fixed.
#
# pre-commit install --hook-type pre-push
#
# but do whatever you like

exclude: 'old/'

fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/pycqa/pylint
  rev: pylint-2.5.0
  hooks:
  - id: pylint
    files: 'jstat/'
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black

# this doesn't seem to quite work...
# - repo: local
#   hooks:
#     - id: tests
#       name: run tests
#       entry: pytest
#       language: system
#       types: [python]
